name:                lambda-pi
version:             0.1.0.0
github:              "oshmkufa2010/lambda-pi"
license:             BSD3
author:              "oshmkufa2010"
maintainer:          "cailinunix@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oshmkufa2010/lambda-pi#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- hspec
- megaparsec
- transformers
- BNFC
- array

library:
  source-dirs: src

executables:
  lambda-pi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-pi

tests:
  lambda-pi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-pi

default-extensions:
- ConstraintKinds
- DataKinds
- FlexibleContexts
- GADTs
- KindSignatures
- LambdaCase
- Rank2Types
- ScopedTypeVariables
- TypeFamilies
- ApplicativeDo
